# Generated by Django 2.0.6 on 2018-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_icon', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=20)),
                ('degree', models.SmallIntegerField()),
                ('cloud_percentage', models.SmallIntegerField()),
                ('windspeed', models.SmallIntegerField()),
                ('wind_direction', models.CharField(max_length=20)),
            ],
        ),
    ]
